  - name: nginx installed
    apt:
      name: nginx
      state: present
      update_cache: yes
    become: true

  - name: nginx systemd module enabled
    systemd:
      name: nginx
      state: started
      enabled: yes
    become: true

  - name: nginx config copied
    copy:
      src: nginx-champions.conf
      dest: /etc/nginx/conf.d/champions.conf
    become: true
    notify: "nginx systemd module restarted"

  - name: static index.html rendered
    template:
      src: nginx-index.html.j2
      dest: /var/www/html/index.html
    become: true

