  - name: systemd modules reloaded
    systemd:
      daemon_reload: yes
    become: true
    changed_when: true
    
  - name: haproxy systemd module restarted
    systemd:
      name: haproxy
      state: restarted
      enabled: yes
    become: true